name: wow_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  table_calendar: ^3.0.8
  syncfusion_flutter_charts: ^21.1.41
  intl: ^0.18.1
  http_parser: ^4.0.2
  fl_chart: ^0.65.0 # Updated to latest version
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^5.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1 # Add this for Hive type generation
  build_runner: ^2.4.6 # Needed for code generation

flutter:
  uses-material-design: true
  assets:
    - assets/images/welcomepage.png
