// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvzaBs7nVg_IbaVcKmaBJp4JZxOd6p_Nk',
    appId: '1:929698661622:web:f904e660e8d3959f3598d7',
    messagingSenderId: '929698661622',
    projectId: 'wow-app-8e32b',
    authDomain: 'wow-app-8e32b.firebaseapp.com',
    storageBucket: 'wow-app-8e32b.firebasestorage.app',
    measurementId: 'G-BTTKWYVK0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApWsnfwpV5p7q8AMvE8DJ8sInLAPnEFVk',
    appId: '1:929698661622:android:a9317be87a5da9143598d7',
    messagingSenderId: '929698661622',
    projectId: 'wow-app-8e32b',
    storageBucket: 'wow-app-8e32b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Pw4Kr_Hit1kdTSAXHP1rpNIDnVazg7I',
    appId: '1:929698661622:ios:e9b17985c86dde3a3598d7',
    messagingSenderId: '929698661622',
    projectId: 'wow-app-8e32b',
    storageBucket: 'wow-app-8e32b.firebasestorage.app',
    iosBundleId: 'com.example.wowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_Pw4Kr_Hit1kdTSAXHP1rpNIDnVazg7I',
    appId: '1:929698661622:ios:e9b17985c86dde3a3598d7',
    messagingSenderId: '929698661622',
    projectId: 'wow-app-8e32b',
    storageBucket: 'wow-app-8e32b.firebasestorage.app',
    iosBundleId: 'com.example.wowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvzaBs7nVg_IbaVcKmaBJp4JZxOd6p_Nk',
    appId: '1:929698661622:web:37d50d4940c3f2143598d7',
    messagingSenderId: '929698661622',
    projectId: 'wow-app-8e32b',
    authDomain: 'wow-app-8e32b.firebaseapp.com',
    storageBucket: 'wow-app-8e32b.firebasestorage.app',
    measurementId: 'G-84MHFC2TYZ',
  );
}
